version: '3.1'

volumes:
  db_data:

services:
  mysql:
    container_name: mysql_${MYSQL_VERSION:-5.7}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASS: ${MYSQL_PASS:-password}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
